replicaCount: 1

image:
  repository: pod-echo
  tag: "0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
