name: PathID assignment

on:
  workflow_dispatch: {}

env:
  IMAGE_NAME: pod-echo
  IMAGE_TAG: "0.1"
  KIND_CLUSTER: pathid
  TF_DIR: .

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Install kind (act only)
        if: ${{ env.ACT }}
        run: |
          curl -Lo /usr/local/bin/kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
          chmod +x /usr/local/bin/kind

      - name: Install kubectl (act only)
        if: ${{ env.ACT }}
        run: |
          curl -sSL -o kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl && mv kubectl /usr/local/bin/kubectl

      - name: Build Docker image
        run: docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .

      - name: Prepare kubeconfig (act only)
        if: ${{ env.ACT }}
        run: |
          echo "KUBECONFIG=/root/.kube/kind-pathid.yaml" >> $GITHUB_ENV
          echo "TF_VAR_kubeconfig_path=/root/.kube/kind-pathid.yaml" >> $GITHUB_ENV
          test -f /root/.kube/kind-pathid.yaml || (echo "missing kubeconfig" && exit 1)

      - name: Load image into Kind (act only)
        if: ${{ env.ACT }}
        run: |
          kind load docker-image ${IMAGE_NAME}:${IMAGE_TAG} --name ${KIND_CLUSTER}
          kubectl cluster-info

      - name: Terraform init/plan/apply
        env:
          TF_IN_AUTOMATION: "true"
          TF_VAR_image_repo: ${{ env.IMAGE_NAME }}
          TF_VAR_image_tag:  ${{ env.IMAGE_TAG }}
        run: |
          terraform -chdir=${TF_DIR} init
          terraform -chdir=${TF_DIR} plan -out=tf.plan
          terraform -chdir=${TF_DIR} apply -auto-approve tf.plan
